In [1]:
from scipy.linalg import solve_banded,lu_factor
import scipy
import numpy as np

The history saving thread hit an unexpected error (DatabaseError('database disk image is malformed')).History will not be written to the database.


In [2]:
N=100

In [3]:
b=np.full(N, 1)

In [4]:
def maxtrixA(N):
    A=np.full((N,N),0)
    a=np.array([1,-4,6,-4,1])
    for i in np.arange(N-4):
        for j in np.arange(5):
            A[2+i][j+i]=a[j]

    A[0][0]=9
    A[0][1]=-4
    A[0][2]=1
    A[1][0]=-4
    A[1][1]=6
    A[1][2]=-4
    A[1][3]=1

    A[N-1][N-1]=1
    A[N-1][N-2]=-2
    A[N-1][N-3]=1
    A[N-2][N-1]=-2
    A[N-2][N-2]=5
    A[N-2][N-3]=-4
    A[N-2][N-4]=1
    
    return A

In [5]:
A=maxtrixA(N)

In [6]:
def solver_bandmatrix1(A,b,N):
    ab=np.full((5,N), 0)
    for i in np.arange(N):
        if i+2<N:
            ab[0][i+2]=A[i][i+2]
            ab[4][i]=A[i+2][i]
        if i+1<N:
            ab[1][i+1]=A[i][i+1]
            ab[3][i]=A[i+1][i]    
        ab[2][i]=A[i][i]
    
    x = scipy.linalg.solve_banded((2, 2), ab, b)
    
    return x    

In [7]:
def solver_bandmatrix2(A,b,N):
    ab=np.full((5,N), 0)
    for i in np.arange(N):
        if i<N-2:
            ab[0][i+2]=A[i][i+2]
            ab[1][i+1]=A[i][i+1]
            ab[2][i]=A[i][i]
            ab[3][i]=A[i+1][i]
            ab[4][i]=A[i+2][i]
            continue
        
        if i==N-2:
            ab[1][i+1]=A[i][i+1]
            ab[2][i]=A[i][i]
            ab[3][i]=A[i+1][i]
            continue
            
        elif i==N-1:
            ab[2][i]=A[i][i]
            continue
    x = scipy.linalg.solve_banded((2, 2), ab, b)
    
    return x 

In [8]:
def LU_decompositon(A,b):
    lu, piv = scipy.linalg.lu_factor(A)
    x = scipy.linalg.lu_solve((lu, piv), b)
    
    return x 

In [9]:
x1=solver_bandmatrix2(A,b,N)
x2=LU_decompositon(A,b)

In [10]:
x1

array([1.26250000e+03, 7.47500000e+03, 1.85385000e+04, 3.43550000e+04,
       5.48275000e+04, 7.98600000e+04, 1.09357500e+05, 1.43226000e+05,
       1.81372500e+05, 2.23705000e+05, 2.70132500e+05, 3.20565000e+05,
       3.74913500e+05, 4.33090000e+05, 4.95007500e+05, 5.60580000e+05,
       6.29722500e+05, 7.02351000e+05, 7.78382500e+05, 8.57735000e+05,
       9.40327500e+05, 1.02608000e+06, 1.11491350e+06, 1.20675000e+06,
       1.30151250e+06, 1.39912500e+06, 1.49951250e+06, 1.60260100e+06,
       1.70831750e+06, 1.81659000e+06, 1.92734750e+06, 2.04052000e+06,
       2.15603850e+06, 2.27383500e+06, 2.39384250e+06, 2.51599500e+06,
       2.64022750e+06, 2.76647600e+06, 2.89467750e+06, 3.02477000e+06,
       3.15669250e+06, 3.29038500e+06, 3.42578850e+06, 3.56284500e+06,
       3.70149750e+06, 3.84169000e+06, 3.98336750e+06, 4.12647600e+06,
       4.27096250e+06, 4.41677500e+06, 4.56386250e+06, 4.71217500e+06,
       4.86166350e+06, 5.01228000e+06, 5.16397750e+06, 5.31671000e+06,
      

In [11]:
x2

array([1.26250000e+03, 7.47500000e+03, 1.85385000e+04, 3.43550000e+04,
       5.48275000e+04, 7.98600000e+04, 1.09357500e+05, 1.43226000e+05,
       1.81372500e+05, 2.23705000e+05, 2.70132500e+05, 3.20565000e+05,
       3.74913500e+05, 4.33090000e+05, 4.95007500e+05, 5.60580000e+05,
       6.29722500e+05, 7.02351000e+05, 7.78382500e+05, 8.57735000e+05,
       9.40327500e+05, 1.02608000e+06, 1.11491350e+06, 1.20675000e+06,
       1.30151250e+06, 1.39912500e+06, 1.49951250e+06, 1.60260100e+06,
       1.70831750e+06, 1.81659000e+06, 1.92734750e+06, 2.04052000e+06,
       2.15603850e+06, 2.27383500e+06, 2.39384250e+06, 2.51599500e+06,
       2.64022750e+06, 2.76647600e+06, 2.89467750e+06, 3.02477000e+06,
       3.15669250e+06, 3.29038500e+06, 3.42578850e+06, 3.56284500e+06,
       3.70149750e+06, 3.84169000e+06, 3.98336750e+06, 4.12647600e+06,
       4.27096250e+06, 4.41677500e+06, 4.56386250e+06, 4.71217500e+06,
       4.86166350e+06, 5.01228000e+06, 5.16397750e+06, 5.31671000e+06,
      

In [12]:
a1=np.dot(A, x1)
a2=np.dot(A, x2)

e1=np.abs(a1-1)
e2=np.abs(a2-1)

accurate11=e1.sum()
accurate22=e2.sum()

print(accurate11)
print(accurate22)

1.642692950554192e-07
1.5647674445062876e-07


In [13]:
x1==x2


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [58]:
%timeit solver_bandmatrix1(A,b,N)

659 µs ± 87.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [59]:
%timeit solver_bandmatrix2(A,b,N)

575 µs ± 44.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
%timeit LU_decompositon(A,b)

200 µs ± 3.11 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [14]:
def matrixR(N):
    R=np.full((N,N),0)
    r=np.array([1,-2,1])
    for i in np.arange(N-3):
        for j in np.arange(3):
            R[1+i][j+i+1]=r[j]

    R[0][0]=2
    R[0][1]=-2
    R[0][2]=1

    R[N-1][N-1]=1
    R[N-2][N-1]=-2
    R[N-2][N-2]=1
    
    return R

In [15]:
R=matrixR(N)

In [16]:
RT=R.transpose()

In [17]:
A4=R.dot(RT)
print(np.array_equal(A4,A))

True


In [104]:
N=1000

In [105]:
b=np.full(N, 1)

A=maxtrixA(N)
R=matrixR(N)
RT=R.transpose()

In [106]:
def UL_factorization(U,L,b,N):
    y=np.full(N, 0)
    x=np.full(N, 0)
    for j in range(N-1,-1,-1):
        if ( U[j][j] == 0 ): break

        y[j] = b[j]/U[j][j]

        for i in range(j):
            b[i]=b[i]-U[i][j]*y[j]
    
    for j in range(N):
        if ( L[j][j] == 0 ): break

        x[j] = y[j]/L[j,j]

        for i in range(j,N):
            y[i]=y[i]-L[i][j]*x[j]
            
    return x

In [107]:
def cho_factorization(A,b):
    c, low = scipy.linalg.cho_factor(A)
    x = scipy.linalg.cho_solve((c, low), b)
    return x

In [108]:
X1=UL_factorization(R,RT,b,N)
b=np.full(N, 1)
X2=cho_factorization(A,b)
b=np.full(N, 1)
X3=solver_bandmatrix2(A,b,N)

In [109]:
acc1=np.dot(A, X1)
acc2=np.dot(A, X2)
acc3=np.dot(A, X3)

In [111]:
error1=np.abs(acc1-1)
error2=np.abs(acc2-1)
error3=np.abs(acc3-1)

In [112]:
accurate1=error1.sum()
accurate2=error2.sum()
accurate3=error3.sum()

In [117]:
print ("The error of using UL_factorization: %f" %accurate1)
print ("The error of using cho_factorization: %f" %accurate2)
print ("The error of using solver_bandmatrix2: %f" %accurate3)

The error of using UL_factorization: 0.000000
The error of using cho_factorization: 0.019947
The error of using solver_bandmatrix2: 0.015274


In [114]:
%timeit UL_factorization(R,RT,b,N)

/home/kevinyu/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: RuntimeWarning: overflow encountered in long_scalars
/home/kevinyu/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: overflow encountered in long_scalars
  # Remove the CWD from sys.path while we load stuff.


802 ms ± 61.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [115]:
%timeit cho_factorization(A,b)

10.5 ms ± 536 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [116]:
%timeit solver_bandmatrix2(A,b,N)

4.74 ms ± 164 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
np.linalg.cond(A)